{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Financial year 2019/2020", "source": "https://www.changiairport.com/corporate/sustainability/sustainable-changi.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/articles/3.%20200416%20-%20A%20cool%20$65k%20for%20ST%20fund%20to%20help%20kids.pdf", "link_text": "A cool $65k for ST fund to help kids", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG%20SUSTAINABILITY%20REPORT%202021.pdf", "link_text": "Financial year 2020/2021", "source": "https://www.changiairport.com/corporate/sustainability/sustainable-changi.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/2-April-2020-Changi-Foundation-CNA.pdf", "link_text": "'Self-disinfecting coating' applied to HDB lift buttons", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2019/9-Oct-2019-Changi-Foundation-ST.pdf", "link_text": "249 top donors and partners recognised for contributions to Community Chest", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-April-2020-Changi-Foundation-Today-Online.pdf", "link_text": "All HDB lift buttons treated with coating agent said to help fend off likes of Covid-19 for up to 3 months", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/23-Aug-2020-Changi-Foundation.pdf", "link_text": "Virtual volunteering: CAG employees role-play as doctor and nurses to help special needs students from Metta School with seeking medical consultation online", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/articles/2%20.031217%20-%20Global%20showcase%20for%20artists%20with%20disabilities.pdf", "link_text": "Global showcase for artists with disabilities", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi%20Foundation%20FY20%20Annual%20Report.pdf", "link_text": "Annual Report - Financial Year 2020/21", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/8-May-2020-Changi-Foundation-beritaharian.pdf", "link_text": "Computer and Wifi assistance (Mujur dapat bantuan komputer dan Wi-Fi)", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi-Foundation-Annual-Report.pdf", "link_text": "Annual Report - Financial Year 2019/20", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-Apr-2020-Changi-Foundation-ST.pdf", "link_text": "Durable, self-disinfecting coating applied on all HDB lift buttons", "source": "https://www.changiairport.com/corporate/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020", "source": "https://www.changiairport.com/corporate/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020 here", "source": "https://www.changiairport.com/corporate/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG%20SUSTAINABILITY%20REPORT%202021.pdf", "link_text": "Financial year 2020/2021", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/articles/3.%20200416%20-%20A%20cool%20$65k%20for%20ST%20fund%20to%20help%20kids.pdf", "link_text": "A cool $65k for ST fund to help kids", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Financial year 2019/2020", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/2-April-2020-Changi-Foundation-CNA.pdf", "link_text": "'Self-disinfecting coating' applied to HDB lift buttons", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi-Foundation-Annual-Report.pdf", "link_text": "Annual Report - Financial Year 2019/20", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://gallery.changiairport.com/content/dam/cacorp/publications/Annual%20Reports/2015/Changi_Airport_Group_Annual_Report_2015_Full-Report.pdf", "link_text": "Full Report", "source": "https://gallery.changiairport.com/"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/8-May-2020-Changi-Foundation-beritaharian.pdf", "link_text": "Computer and Wifi assistance (Mujur dapat bantuan komputer dan Wi-Fi)", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/articles/2%20.031217%20-%20Global%20showcase%20for%20artists%20with%20disabilities.pdf", "link_text": "Global showcase for artists with disabilities", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-Apr-2020-Changi-Foundation-ST.pdf", "link_text": "Durable, self-disinfecting coating applied on all HDB lift buttons", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi%20Foundation%20FY20%20Annual%20Report.pdf", "link_text": "Annual Report - Financial Year 2020/21", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-April-2020-Changi-Foundation-Today-Online.pdf", "link_text": "All HDB lift buttons treated with coating agent said to help fend off likes of Covid-19 for up to 3 months", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/23-Aug-2020-Changi-Foundation.pdf", "link_text": "Virtual volunteering: CAG employees role-play as doctor and nurses to help special needs students from Metta School with seeking medical consultation online", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://community.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2019/9-Oct-2019-Changi-Foundation-ST.pdf", "link_text": "249 top donors and partners recognised for contributions to Community Chest", "source": "https://community.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-Apr-2020-Changi-Foundation-ST.pdf", "link_text": "Durable, self-disinfecting coating applied on all HDB lift buttons", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/articles/3.%20200416%20-%20A%20cool%20$65k%20for%20ST%20fund%20to%20help%20kids.pdf", "link_text": "A cool $65k for ST fund to help kids", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/2-April-2020-Changi-Foundation-CNA.pdf", "link_text": "'Self-disinfecting coating' applied to HDB lift buttons", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2019/9-Oct-2019-Changi-Foundation-ST.pdf", "link_text": "249 top donors and partners recognised for contributions to Community Chest", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-April-2020-Changi-Foundation-Today-Online.pdf", "link_text": "All HDB lift buttons treated with coating agent said to help fend off likes of Covid-19 for up to 3 months", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/23-Aug-2020-Changi-Foundation.pdf", "link_text": "Virtual volunteering: CAG employees role-play as doctor and nurses to help special needs students from Metta School with seeking medical consultation online", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/articles/2%20.031217%20-%20Global%20showcase%20for%20artists%20with%20disabilities.pdf", "link_text": "Global showcase for artists with disabilities", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/8-May-2020-Changi-Foundation-beritaharian.pdf", "link_text": "Computer and Wifi assistance (Mujur dapat bantuan komputer dan Wi-Fi)", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi%20Foundation%20FY20%20Annual%20Report.pdf", "link_text": "Annual Report - Financial Year 2020/21", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi-Foundation-Annual-Report.pdf", "link_text": "Annual Report - Financial Year 2019/20", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG%20SUSTAINABILITY%20REPORT%202021.pdf", "link_text": "Financial year 2020/2021", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Financial year 2019/2020", "source": "https://www.changiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020", "source": "https://community.changiairport.com/content/cag-corp/en/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020 here", "source": "https://community.changiairport.com/content/cag-corp/en/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020 here", "source": "https://rewards.changiairport.com/content/cag-corp/en/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020", "source": "https://rewards.changiairport.com/content/cag-corp/en/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/2-April-2020-Changi-Foundation-CNA.pdf", "link_text": "'Self-disinfecting coating' applied to HDB lift buttons", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Financial year 2019/2020", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/8-May-2020-Changi-Foundation-beritaharian.pdf", "link_text": "Computer and Wifi assistance (Mujur dapat bantuan komputer dan Wi-Fi)", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/articles/2%20.031217%20-%20Global%20showcase%20for%20artists%20with%20disabilities.pdf", "link_text": "Global showcase for artists with disabilities", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2019/9-Oct-2019-Changi-Foundation-ST.pdf", "link_text": "249 top donors and partners recognised for contributions to Community Chest", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/articles/3.%20200416%20-%20A%20cool%20$65k%20for%20ST%20fund%20to%20help%20kids.pdf", "link_text": "A cool $65k for ST fund to help kids", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi-Foundation-Annual-Report.pdf", "link_text": "Annual Report - Financial Year 2019/20", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/23-Aug-2020-Changi-Foundation.pdf", "link_text": "Virtual volunteering: CAG employees role-play as doctor and nurses to help special needs students from Metta School with seeking medical consultation online", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG%20SUSTAINABILITY%20REPORT%202021.pdf", "link_text": "Financial year 2020/2021", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi%20Foundation%20FY20%20Annual%20Report.pdf", "link_text": "Annual Report - Financial Year 2020/21", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-Apr-2020-Changi-Foundation-ST.pdf", "link_text": "Durable, self-disinfecting coating applied on all HDB lift buttons", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.jewelchangiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-April-2020-Changi-Foundation-Today-Online.pdf", "link_text": "All HDB lift buttons treated with coating agent said to help fend off likes of Covid-19 for up to 3 months", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020 here", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://www.changiairport.com/content/dam/cacorp/media-centre/6.2%20Resources/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Sustainability Report 2019/2020", "source": "https://www.jewelchangiairport.com/content/cag-corp/en/media-centre/changijourneys/the-airport-never-sleeps/sustainability-report1920.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG-Sustainability%20Report%20FY1920.pdf", "link_text": "Financial year 2019/2020", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/sustainable-changi/sustainability-report/CAG%20SUSTAINABILITY%20REPORT%202021.pdf", "link_text": "Financial year 2020/2021", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/sustainable-changi.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/8-May-2020-Changi-Foundation-beritaharian.pdf", "link_text": "Computer and Wifi assistance (Mujur dapat bantuan komputer dan Wi-Fi)", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/23-Aug-2020-Changi-Foundation.pdf", "link_text": "Virtual volunteering: CAG employees role-play as doctor and nurses to help special needs students from Metta School with seeking medical consultation online", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/articles/3.%20200416%20-%20A%20cool%20$65k%20for%20ST%20fund%20to%20help%20kids.pdf", "link_text": "A cool $65k for ST fund to help kids", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/articles/2%20.031217%20-%20Global%20showcase%20for%20artists%20with%20disabilities.pdf", "link_text": "Global showcase for artists with disabilities", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/2-April-2020-Changi-Foundation-CNA.pdf", "link_text": "'Self-disinfecting coating' applied to HDB lift buttons", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi%20Foundation%20FY20%20Annual%20Report.pdf", "link_text": "Annual Report - Financial Year 2020/21", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Changi-Foundation-Annual-Report.pdf", "link_text": "Annual Report - Financial Year 2019/20", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-Apr-2020-Changi-Foundation-ST.pdf", "link_text": "Durable, self-disinfecting coating applied on all HDB lift buttons", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2019/9-Oct-2019-Changi-Foundation-ST.pdf", "link_text": "249 top donors and partners recognised for contributions to Community Chest", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://rewards.changiairport.com/content/dam/cacorp/sustainability/changi-foundation/Milestones/2020/3-April-2020-Changi-Foundation-Today-Online.pdf", "link_text": "All HDB lift buttons treated with coating agent said to help fend off likes of Covid-19 for up to 3 months", "source": "https://rewards.changiairport.com/content/cag-corp/en/sustainability/changi-foundation.html"}
{"link": "https://unfccc.int/files/national_reports/non-annex_i_natcom/application/pdf/nc3_republic_of_mauritius_20jan17.pdf", "link_text": "7-8%", "source": "https://nowboarding.changiairport.com/go-global/Beautiful-paradise-islands-to-visit.html"}
